baseURL = 'https://diegovel1.github.io/'
languageCode = 'es-co'
title = 'Diego Velásquez'
theme = 'PaperMod'
enableEmoji = true

[params]
env = 'production'
GoogleAnalyticsID = 'G-ZJWEMQMWBG'
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
showtoc = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowWordCount = true
defaultTheme = 'dark'
disableThemeToggle = true
social = true


[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 3
keys = ["title", "permalink", "summary", "content"]

[params.homeInfoParams]
Title = "Notas públicas"
Content = "Sistemas, economía, sociedad. Apuntes de mi cosmología."

[[params.socialIcons]]
name = "x"
url = "https://twitter.com/diegovel11"

[[params.socialIcons]]
name = "github"
url = "https://github.com/diegovel1"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/diegovel9"

[[params.socialIcons]]
name = "youtube"
url = "https://youtube.com/@diegovel2"

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/diegovel.com"

[params.author]
    email = "diegovel1@protonmail.com"

[menu]

[[menu.main]]
identifier = 'entradas'
name = 'Entradas'
url = '/entradas/'
weight = 10

[[menu.main]]
identifier = 'categorias'
name = 'Categorías'
url = '/categories/'
weight = 20

[[menu.main]]
identifier = 'acerca'
name = 'Acerca'
url = '/acerca'
weight = 30

[outputs]
home = ["HTML", "RSS", "JSON"]
