baseURL = 'https://diegovel1.github.io/'
languageCode = 'es-co'
title = 'Sitio web de Diego Velásquez'
theme = 'PaperMod'
enableEmoji = true

[params]
env = 'production'
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
showtoc = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowWordCount = true
defaultTheme = 'dark'
disableThemeToggle = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 3
keys = ["title", "permalink", "summary", "content"]

[params.homeInfoParams]
Title = "Hola."
Content = "Bienvenidos a mi sitio web."

[[params.socialIcons]]
name = "x"
url = "https://twitter.com/diegovel11"

[[params.socialIcons]]
name = "github"
url = "https://github.com/diegovel1"

[params.author]
    email = "diegovel1@protonmail.com"

[menu]

[[menu.main]]
identifier = 'entradas'
name = 'Entradas'
url = '/entradas/'
weight = 10

[[menu.main]]
identifier = 'categorias'
name = 'Categorías'
url = '/categories/'
weight = 20

[[menu.main]]
identifier = 'archivo'
name = 'Archivo'
url = '/archive/'
weight = 30

[[menu.main]]
identifier = 'buscar'
name = 'Buscar'
url = '/search/'
weight = 40

[outputs]
home = ["HTML", "RSS", "JSON"]
